### ISSUE TITLE
Does this plugin support vue3 only?

### ISSUE THREAD

**Issue by kat3su** [rashfael/eslint-plugin-vue-pug#16]
Tried to add this to our Vue 2 project but nothing really changed.

Added npm package and add to `plugin:vue-pug/strongly-recommended` to eslint extends

**Comment by Grawl** [comment]
try to extend from 'plugin:vue-pug/base'

**Comment by rashfael** [comment]
Can you post your full eslint config?

**Comment by kat3su** [comment]
@rashfael It's below in yaml format. tried with and without the `plugins` and not much success.
`<template>{html}</template>` works fine but `<template lang="plug">....</template>` didn't pickup any errors (obvious errors)

```
root: true
parserOptions:
  parser: "@babel/eslint-parser"
  sourceType: module
env:
  serviceworker: true
  browser: true
extends:
  - plugin:vue/strongly-recommended
  - plugin:vue-pug/strongly-recommended
  - standard
  - prettier
plugins:
  - vue
  - vue-plug
  - prettier
globals:
  ga: true
  cordova: true
  __statics: true
rules:
  arrow-parens:
    - error
    - as-needed
  import/first: 0
  import/named: 2
  import/namespace: 2
  import/default: 2
  import/export: 2
  import/extensions: 0
  import/no-unresolved: 0
  import/no-extraneous-dependencies: 0
```

**Comment by Grawl** [comment]
plug?

**Comment by kat3su** [comment]
Was a mistake typing that comment, it is `pug`

**Comment by rashfael** [comment]
You should not need the `vue` and `vue-pug` entries in `plugins` since they are already part of the configs you are extending, but that should not matter.
I'm not sure how deep eslint merges it's configs, you might need to add `templateTokenizer: { pug: 'vue-eslint-parser-template-tokenizer-pug' }` to your parserOptions, like this https://github.com/rashfael/eslint-plugin-vue-pug/blob/main/lib/configs/base.js#L11 . This is the actual part that enables existing eslint-plugin-vue rules to work on pug templates.
